# Generated by Django 5.1.1 on 2024-09-18 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acsapp', '0003_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='taskname',
        ),
    ]
