# Generated by Django 5.1.1 on 2024-09-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acsapp', '0006_archiveduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Working', 'Working'), ('Completed', 'Completed')], default='Not Started', max_length=12),
        ),
    ]
