# Generated by Django 5.1.1 on 2024-09-21 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acsapp', '0007_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acsapp.task'),
            preserve_default=False,
        ),
    ]
