# Generated by Django 5.1.1 on 2024-09-21 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acsapp', '0008_todolist_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='task',
        ),
    ]
